import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    // Redirect to /book page
    router.push("/book");
  }, []); // Empty dependency array ensures the effect runs only once on mount

  return null; // Since this is a redirection page, no content is needed
  return (
    <>
      <Head>
        <title>VIN Automotive Assigment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
}
